# general settings
name: GACNet_L_x4
model_type: SRModel
scale: 4
num_gpu: 1
manual_seed: 0  # 0 or 10

# python basicsr/train.py -opt options/train/train_LKFMixer_x4.yml --auto_resume

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    # dataroot_gt: datasets/hr
    # dataroot_lq: datasets/lrx4
    # (for lmdb)
    dataroot_gt: D:\aaaasr\RGBTDronePerson\train\GT
    dataroot_lq: D:\aaaasr\RGBTDronePerson\train\LR
    filename_tmpl: '{}'
    io_backend:

      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: set5
    type: PairedImageDataset
    dataroot_gt: D:\aaaasr\RGBTDronePerson\val\GT
    dataroot_lq: D:\aaaasr\RGBTDronePerson\val\LR
    io_backend:
      type: disk


# network structures
network_g:
  type: GACNet
  in_channels: 3
  channels: 64
  out_channels: 3
  upscale: 4
  num_block: 1
  large_kernel: 31

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000]
    restart_weights: [1]
    eta_min: !!float 1e-6

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean


# validation settings
val:
  val_freq: 10000
  save_img: true
  self_ensemble_testing: false
  metrics:
    PSNR: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher
    SSIM: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher


# logging settings
logger:
  print_freq: 10000
  save_checkpoint_freq: 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
